/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefetrj.mg.bsi.lista01.view;

import br.cefetrj.mg.bsi.lista01.controller.Exec07Controller;
import br.cefetrj.mg.bsi.lista01.utils.Utils;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import static br.cefetrj.mg.bsi.lista01.utils.Utils.*;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno-2
 */
public class Exec07Form extends javax.swing.JFrame {

    /**
     * Creates new form Exec07Form
     */
    private Exec07Controller controller = null;

    public Exec07Form() {
        initComponents();
        jTxtId.setEditable(false);
        jLblId.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblId = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtIsbn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAutor = new javax.swing.JTextField();
        jBtnCadAtualizar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblId.setText("ID");
        getContentPane().add(jLblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jTxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        getContentPane().add(JTxtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, -1));

        jLabel3.setText("Título");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(jTxtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, -1));

        jLabel4.setText("Autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(jTxtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, -1));

        jBtnCadAtualizar.setText("Cadastrar");
        jBtnCadAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCadAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadAtualizarActionPerformed
        // TODO add your handling code here:
        controller = new Exec07Controller();
        if (!jTxtId.getText().isEmpty()) {
            jBtnCadAtualizar.setText("Atualizar");
            controller.setForm(this);
            Utils.print(controller.atualizar());
        } else {
            jBtnCadAtualizar.setText("Cadastrar");
            controller.setForm(this);
            Utils.print(controller.inserir());

        }
        limpar();
    }//GEN-LAST:event_jBtnCadAtualizarActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // TODO add your handling code here:
        controller = new Exec07Controller();
        if (!jTxtId.isEditable()) {
            jTxtId.setEditable(true);
            jLblId.setEnabled(true);
            jTxtId.requestFocus();

        } else {
            controller.setForm(this);
            controller.buscar();
        }


    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if(Utils.confirm("Deseja realmente excluir?", "Livro")==JOptionPane.YES_OPTION){
            controller =new Exec07Controller();
            controller.setForm(this);
            
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void limpar() {
        JTextField txt[] = {
            JTxtIsbn,
            jTxtAutor,
            jTxtId,
            jTxtTitulo
        };
        for(JTextField t:txt)
            t.setText("");
        jBtnCadAtualizar.setText("Cadastrar");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exec07Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exec07Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exec07Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exec07Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exec07Form().setVisible(true);
            }
        });
    }

    public JTextField getJTxtIsbn() {
        return JTxtIsbn;
    }

    public void setJTxtIsbn(JTextField JTxtIsbn) {
        this.JTxtIsbn = JTxtIsbn;
    }

    public JButton getjBtnBuscar() {
        return jBtnBuscar;
    }

    public void setjBtnBuscar(JButton jBtnBuscar) {
        this.jBtnBuscar = jBtnBuscar;
    }

    public JButton getjBtnCadAtualizar() {
        return jBtnCadAtualizar;
    }

    public void setjBtnCadAtualizar(JButton jBtnCadAtualizar) {
        this.jBtnCadAtualizar = jBtnCadAtualizar;
    }

    public JButton getjBtnExcluir() {
        return jBtnExcluir;
    }

    public void setjBtnExcluir(JButton jBtnExcluir) {
        this.jBtnExcluir = jBtnExcluir;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLblId() {
        return jLblId;
    }

    public void setjLblId(JLabel jLblId) {
        this.jLblId = jLblId;
    }

    public JTextField getjTxtAutor() {
        return jTxtAutor;
    }

    public void setjTxtAutor(JTextField jTxtAutor) {
        this.jTxtAutor = jTxtAutor;
    }

    public JTextField getjTxtId() {
        return jTxtId;
    }

    public void setjTxtId(JTextField jTxtId) {
        this.jTxtId = jTxtId;
    }

    public JTextField getjTxtTitulo() {
        return jTxtTitulo;
    }

    public void setjTxtTitulo(JTextField jTxtTitulo) {
        this.jTxtTitulo = jTxtTitulo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtIsbn;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnCadAtualizar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblId;
    private javax.swing.JTextField jTxtAutor;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtTitulo;
    // End of variables declaration//GEN-END:variables
}
